### PR TITLE
Publish arm64 Docker images

### PR DESCRIPTION
**Pull request by mikery**
This PR updates the Docker workflow to provide `linux/arm64` images. 

Example workflow execution: https://github.com/mikery/base-node/actions/runs/7773045091/job/21196224081

### CODE REVIEW

**Comment by wbnns** [comment]
@mikery 

Thanks for the PR! Adding this to the backlog for the team to review. 👍

**Comment by Mitsuwa** [comment]
Please include these updates to the [pr.yaml](https://github.com/base-org/node/blob/main/.github/workflows/pr.yml) workflow that runs on pr as well to ensure both arch's are also tested on pr's

**Comment by Mitsuwa** [comment]
Using a `matrix` here instead of listing both arch's to buildx will allow the builds to run concurrently and it will be clearer which arch is failing if there is a difference in archs, because they will separate into different jobs,  something like 

image

this will also make it easier in the future to configure any additional steps for the arch if there is ever a need to

**Comment by mdehoog** [comment]
Unfortunately I cannot push to your branch, so I added support for the PR tests here: https://github.com/mikery/base-node/pull/1. Please merge this, and then we can merge this PR.

Alternatively I'll close this PR and open a separate one with the same changes.

**Comment by mikery** [comment]
@mdehoog thanks for the updates, and apologies for the slow response. I've merged your branch into mine.

**Review by mdehoog — APPROVED** [review]
thanks!

**Pull request merged**
