### PR TITLE
Add Issue and PR templates

### PR DESCRIPTION
**Pull request by wbnns**
This PR adds Issue and PR templates to the repository to help organize the way issues and pull requests are opened, by standardizing the type of information that gets submitted.

I pulled these over from the [Coinbase Wallet SDK](https://github.com/coinbase/coinbase-wallet-sdk/tree/master/.github); they're the same ones that are being used there, except refactored for Base. You can [play with opening an issue over there](https://github.com/coinbase/coinbase-wallet-sdk/issues/new/choose) to get an idea of what it looks like. *Note:* I dropped the smartphone-related info from them before adding to this repo since it's not going to be relevant for the purposes of running a node.

When/if #15 is incorporated I would also follow-on to update this in the future to ask users to include a version when opening an issue. I left this section out for now since there is no versioning at present in the repo.

### CODE REVIEW

**Comment by mdehoog** [comment]
Thanks for the contribution. I think for now we'll keep this PR open to see what types of issues folks report so we can get a better understanding of a good set of form inputs, rather than copying directly from the Wallet SDK, which I think has a slightly different audience.

**Comment by wbnns** [comment]
@mdehoog

Ok, copy, thanks for the review!

**Comment by RithTK** [comment]
good

**Comment by wbnns** [comment]
Since it has been some time going to go ahead and close this. Not sure we need it but happy to bring back/reopen if requested or circumstances change. 👍

**Pull request closed without merging**
